# Generated by Django 2.1.7 on 2019-05-21 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Glasses', 'Glasses'), ('Shoes', 'Shoes')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Lifestyle', 'Lifestyle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
